name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: public
          clean: true
